# Hysteresis configuration (generated post DEC-20250812-02 adoption)
version: 1.0.0
dec_id: DEC-20250812-02
parameters:
  T_enter_major: 0.50
  T_enter_standard: 0.60
  consecutive_required_standard: 2
  T_exit: 0.65
  cooldown_snapshots_after_exit: 1
  stalled_window_snapshots: 5
  stalled_min_ratio: 0.55
  stalled_max_ratio_below_exit: 0.65
  anomaly_delta_threshold_equity_ratio: 0.03   # Referenced; confirm via anomaly DEC if needed
  anomaly:
    delta_threshold: 0.03           # magnitude of ratio change to consider
    min_samples: 5                  # require at least N snapshots before detecting
    consecutive_required: 2         # require N consecutive deltas above threshold
    cooldown_snapshots: 3           # suppress alerts for N snapshots after an anomaly
  smoothing_alpha: 0.3            # EMA smoothing factor (0..1), 0=off if <=0
  # TWD partitioning config
  phi_k: 0.01                     # logistic scale for mapping (|delta|-thr)
  phi_window: 20                  # rolling window size for phi statistics
  lambda: 1.0                     # dynamic threshold width multiplier (μ±λσ)
  alpha_beta_min_gap: 0.10        # enforce minimal α/β separation when σ≈0
  # Toggling guard
  guard_window: 12                # sliding window length (snapshots)
  guard_max_alerts: 2             # max anomalies allowed within the window
state_labels_internal: [NONE, CANDIDATE, ACTIVE, STALLED, CLEARED]
entry_reasons: [severe, consecutive]
enforcement:
  lock_policy: hysteresis.params.lock
  on_mismatch:
    strategy: warn_first_then_fail_after
    threshold_consecutive: 2   # number of consecutive mismatches before failing CI
hash_sha256_manifest_ref: "<PENDING_HASH (spec-hash-manifest-v1.json entry)>"  # Will be reconciled by CI; do not edit manually once filled.
integrity_notes:
  - "Any parameter change requires new DEC and version increment (1.0.x -> 1.1.0 if threshold semantics change)."
  - "Policy hysteresis.params.lock compares runtime constants to this file's parsed values."