name: CI Guard (H1)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  h1-guard:
  # Run for:
  # - push (always)
  # - pull_request (except Dependabot)
  # - pull_request_target (Dependabot only)
  if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]') || (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout (PR/Push)
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout base for Dependabot (PR Target)
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (CI)
        run: npm ci

      - name: Run H1 guard (fairness, snapshots, anomalies, KPIs, perf, a11y)
        run: node tools/h1-verify-guard.js
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_ACTOR: ${{ github.actor }}
          PR_HEAD_REF: ${{ github.head_ref || github.event.pull_request.head.ref || '' }}
          PERF_ADVISORY: ${{ (github.actor == 'dependabot[bot]') || startsWith(github.head_ref, 'dependabot/') || (github.event.pull_request.head.ref && startsWith(github.event.pull_request.head.ref, 'dependabot/')) }}

      - name: Terminology Adoption Enforcement (warning mode)
        continue-on-error: true
        run: |
          ADOPTION_MIN=80 BANNED_MAX=0 node tools/terminology-adoption.js

      - name: npm audit (high severity)
        run: |
          npm audit --audit-level=high || echo "npm audit found issues (non-blocking)"

      - name: Upload KPI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: h1-kpi-artifacts
          path: |
            artifacts/h1-kpi-summary.json
            artifacts/weekly-trends.json
            artifacts/equity-anomalies.json
            artifacts/under-served.json
            artifacts/a11y-smoke-report.json
            artifacts/perf-budget-report.json
