name: H1 Guard & KPI

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  h1-guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run H1 Guard
        run: |
          node tools/h1-verify-guard.js

      - name: Terminology Adoption Enforcement
        run: |
          ADOPTION_MIN=80 BANNED_MAX=0 node tools/terminology-adoption.js

      - name: Perf & A11y Smokes
        run: |
          node tools/perf-budget-smoke.js
          node tools/a11y-smoke.js

      - name: Rebuild KPI Summary (include adoption)
        run: |
          node tools/generate-h1-kpi-summary.js
          node tools/monthly-feedback-rollup.js

      - name: UI Smoke Test (Equity)
        run: |
          node tools/tests/equity-ui-smoke.test.js

      - name: Upload KPI & Equity Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: h1-kpi
          path: |
            artifacts/h1-kpi-summary.json
            artifacts/equity-summary.json
            artifacts/equity-anomalies.json
            artifacts/under-served.json
            artifacts/feedback-monthly-rollup.json

      - name: Chain Integrity Monitor (advisory)
        run: |
          node tools/chain-monitor.js || echo "chain-monitor failed (advisory)"

      - name: Upload Chain Monitor Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: chain-monitor
          path: artifacts/chain-monitor.json
