name: Phase Tracker

on:
  schedule:
    - cron: "0 * * * *" # hourly
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  phase-tracker:
    runs-on: ubuntu-latest
    env:
      PHASE_TRACKER_TOKEN: ${{ secrets.PHASE_TRACKER_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Generate Phase Tracker
        run: |
          node tools/generate-phase-tracker.js
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: phase-tracker
          path: artifacts/phase-tracker.json
      - name: Commit (optional auto-update)
        run: |
          if git diff --quiet artifacts/phase-tracker.json; then
            echo "No phase change."
          else
            echo "Phase change detected; will open PR."
          fi
      - name: Preflight – check PAT secret (PHASE_TRACKER_TOKEN)
        if: env.PHASE_TRACKER_TOKEN == ''
        run: |
          echo "::warning::PHASE_TRACKER_TOKEN is not set. Skipping PR creation."
          echo "To enable automated PRs, add a repo secret named PHASE_TRACKER_TOKEN with a Fine-grained PAT (Contents: Read and write; Pull requests)."
      - name: Create PR for phase tracker update (using PAT)
        if: ${{ !cancelled() && env.PHASE_TRACKER_TOKEN != '' }}
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update phase-tracker"
          title: "chore: update phase-tracker"
          body: |
            Automated hourly update to artifacts/phase-tracker.json.

            - See artifact in this workflow run
          labels: "automation,governance"
          branch: chore/phase-tracker
          base: main
          add-paths: |
            artifacts/phase-tracker.json
          token: ${{ env.PHASE_TRACKER_TOKEN }}