name: PR Label Recommendations

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  recommend-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Generate recommendations
        run: node tools/pr-label-advisor.js
      - name: Upload recommendations
        uses: actions/upload-artifact@v4
        with:
          name: pr-label-recommendations
          path: artifacts/pr-label-recommendations.json
